### PR TITLE
Setup some infrastructure for the repository. 

### PR DESCRIPTION
**Pull request by tannergooding**
This is the same infrastructure setup that was done for ClangSharp in https://github.com/microsoft/ClangSharp/pull/60, but it additionally removes the now unneeded custom libLLVM support.

### CODE REVIEW

**Comment by tannergooding** [comment]
This also removes the now outdated/checked in copy of ClangSharpPInvokeGenerator (which is the bulk of the diff).

**Comment by tannergooding** [comment]
Seems I broke travis, will investigate shortly.

**Comment by tannergooding** [comment]
Got most things resolved (namely forgetting to mark shell scripts as executable), but libLLVM still can't be found when running tests. It's passing locally on a clean machine (both Windows and Linux), so I'm still trying things out...

**Comment by tannergooding** [comment]
It might be because the CI is running on "trusty" and I upgraded the PackageReference from 5.0.1 to 7.0.1...

**Comment by tannergooding** [comment]
Ok. Some dependency of libLLVM 7.0.1 is missing from the Travis CI machines. I tested up to bionic, and they all failed.

That, unfortunately, means that the CI tests are validating much older LLVM bits.

**Comment by tannergooding** [comment]
I've squashed the additional changes into a single commit to make reviewing them easier. I've also attempted to keep LLVMSharp targeting 7.0.1 (so the nuget package is more correct) while keeping LLVMSharp.UnitTests targeting 5.0.1 (so tests in CI can pass).

**Comment by mjsabby** [comment]
Thanks. We should talk offline about dnceng vs getting our own instance. And then retiring this Travis CI system.

**Comment by mjsabby** [comment]
By talk I mean ... nudging the relevant folks more :)

**Pull request merged**
