### PR TITLE
Fix signature of ConstIntOfArbitraryPrecision

### LINKED ISSUE #63: Wrong signature of LLVM.ConstIntOfArbitraryPrecision?
[LLVM documentation says](http://llvm.org/doxygen/group__LLVMCCoreValueConstantScalar.html#ga3ce3363ae52e157bbc63c9fde4aa3821) that the last parameter of `LLVMConstIntOfArbitraryPrecision()` is `const uint64_t[]` but we have it as `int[]`. I think it should be `ulong[]`.

### PR DESCRIPTION
**Pull request by am11**
Fix #63

### CODE REVIEW

**Comment by ice1000** [comment]
Please merge this :sob:

**Comment by TChatzigiannakis** [comment]
LGTM.

**Comment by am11** [comment]
Could we get package update?

**Comment by mjsabby** [comment]
@am11 now that LLVM 6.0.0 is out, I'll make a new one.

**Pull request merged**
