### PR TITLE
Update sample projects according to the newest LLVM# API + .Net Core 2.0

### PR DESCRIPTION
**Pull request by ice1000**
And fix some stupid errors. :joy:

### CODE REVIEW

**Comment by ice1000** [comment]
I also recommend you to make the use of Travis CI.

**Comment by ice1000** [comment]
My last commit ask Travis CI to build LLVM#. Travis CI will only send you email when you pushed uncompilable code(rather than simply `build fail`).

**Comment by ice1000** [comment]
@mjsabby @martinwoodward :smile: Please carefully review and merge my pull request

**Comment by mjsabby** [comment]
@ice1000 can you squash merge into a single commit? Also, is there a reason why you removed "this." from your changes?

**Comment by ice1000** [comment]
>  is there a reason why you removed "this." from your changes?

It's..ahh just personal reason. I'll revert those changes.

> squash

Can you do this as the merger? I've seen the github blog and it says there's a button like this

**Comment by ice1000** [comment]
All `this.` are reverted.

**Comment by ice1000** [comment]
@mjsabby :smiley: CI check done. Everything's ready

**Comment by mjsabby** [comment]
Thanks @ice1000, merged.

**Pull request merged**
